// This file is generated by Slice Machine. Update with care!

import HeroBlock from './HeroBlock';
import Image from './Image';
import ImageGallery from './ImageGallery';
import PageIntro from './PageIntro';
import Text from './Text';

export {
	HeroBlock,
	Image,
	ImageGallery,
	PageIntro,
	Text,
};

export const components = {
	hero_block: HeroBlock,
	image: Image,
	image_gallery: ImageGallery,
	page_intro: PageIntro,
	text: Text,
};
